# Generated by Django 4.2 on 2023-05-06 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.IntegerField()),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hr51', max_length=30)),
                ('owner', models.CharField(default='karan bhadana', max_length=20)),
                ('location', models.CharField(default='faridabad', max_length=50)),
                ('state', models.CharField(default='haryana', max_length=50)),
                ('country', models.CharField(default='india', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('1', 'premium'), ('2', 'deluxe'), ('3', 'basic')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'available'), ('2', 'not available')], max_length=15)),
                ('roomnumber', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.hotels')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booking_id', models.CharField(default='null', max_length=100)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('property_type', models.CharField(choices=[('1', 'semi_furnished'), ('2', 'fully_furnished'), ('3', 'luxury'), ('4', 'basic')], max_length=50)),
                ('property_status', models.CharField(choices=[('1', 'available for sell'), ('2', 'available for rent/lease'), ('3', 'not available')], max_length=15)),
                ('property_room', models.CharField(choices=[('1', '1BHK'), ('2', '2BHK'), ('3', '3BHK'), ('4', '4BHK'), ('5', '5BHK'), ('6', '6BHK'), ('7', '7BHK')], max_length=15)),
                ('ownership', models.CharField(choices=[('1', 'first_ownership'), ('2', 'second_ownership'), ('3', 'third_ownership'), ('4', 'multiple_ownership')], max_length=15)),
                ('location', models.CharField(default='faridabad', max_length=50)),
                ('property_price', models.IntegerField()),
                ('property_size', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post/')),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.category')),
            ],
        ),
    ]
