# Generated by Django 4.2 on 2023-05-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_remove_post_property_type_alter_post_ownership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ownership',
        ),
    ]
