# Generated by Django 4.2 on 2023-05-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_remove_post_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('rooms', models.CharField(max_length=15)),
                ('ownership', models.CharField(max_length=15)),
                ('location', models.CharField(default='faridabad', max_length=50)),
                ('property_price', models.IntegerField()),
                ('property_size', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post/')),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
