# Generated by Django 4.2 on 2023-05-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_property_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ownership',
            field=models.CharField(choices=[('1', 'first_ownership'), ('2', 'second_ownership'), ('3', 'third_ownership'), ('4', 'multiple_ownership')], max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.CharField(choices=[('1', '1BHK'), ('2', '2BHK'), ('3', '3BHK'), ('4', '4BHK'), ('5', '5BHK'), ('6', '6BHK'), ('7', '7BHK')], max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('1', 'available for sell'), ('2', 'available for rent/lease'), ('3', 'not available')], max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('1', 'semi_furnished'), ('2', 'fully_furnished'), ('3', 'luxury'), ('4', 'basic')], max_length=50),
        ),
    ]
