# Generated by Django 4.2 on 2023-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_alter_property_ownership_alter_property_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
