# Generated by Django 4.2 on 2023-05-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_property_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_rooms',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='blockarea',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='building_type',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='closed_parking',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='loan_available',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='locality',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='possession_status',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='view',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
