# Generated by Django 4.2 on 2023-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_rooms_image_rooms_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='property_bhk',
            field=models.CharField(choices=[('1', '1BHK'), ('2', '2BHK'), ('3', '3BHK'), ('4', '4BHK'), ('5', '5BHK'), ('6', '6BHK'), ('7', '7BHK')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
