# Generated by Django 4.2 on 2023-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_rooms_property_bhk_rooms_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='bathroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='bedroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='content',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='ownership',
            field=models.CharField(choices=[('1', 'First Owner'), ('2', 'Second Owners'), ('3', 'Third Owners'), ('4', 'Multiple Owners')], max_length=150, null=True),
        ),
    ]
