# Generated by Django 4.2 on 2023-05-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_rooms_address_rooms_bathroom_rooms_bedroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='bedroom',
        ),
        migrations.AddField(
            model_name='rooms',
            name='Configuration',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='consider',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='facing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='flooring',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='furnished_details',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='nearby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='parking',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='powerbackup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='property_age',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='propety_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='water_source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='widthroad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='ownership',
            field=models.CharField(choices=[('1', 'First Owner'), ('2', 'Second Owners'), ('3', 'Third Owners'), ('4', 'FreeHold'), ('5', 'Multiple Owners')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=15),
        ),
    ]
