# Generated by Django 4.2 on 2023-05-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_remove_rooms_bathroom_remove_rooms_bedroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='map',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
