# Generated by Django 4.2 on 2023-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_rooms_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image1',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image2',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image3',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image4',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image5',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image6',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image7',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
    ]
