# Generated by Django 4.2 on 2023-05-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0015_rooms_image1_rooms_image2_rooms_image3_rooms_image4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='image7',
        ),
    ]
