# Generated by Django 4.2 on 2023-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0016_remove_rooms_image5_remove_rooms_image6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='yearbuild',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomnumber',
            field=models.IntegerField(null=True),
        ),
    ]
