# Generated by Django 4.2 on 2023-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0017_rooms_yearbuild_alter_rooms_roomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='prop_status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='prop_type',
            field=models.CharField(choices=[('1', 'Independent Builder Floor'), ('2', 'Builder Floor'), ('3', 'Not Available')], max_length=50, null=True),
        ),
    ]
