# Generated by Django 4.2 on 2023-05-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0018_rooms_prop_status_rooms_prop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='location',
            field=models.CharField(default='Faridabad', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(default='HR51', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='owner',
            field=models.CharField(default='Karan Bhadana', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='Haryana', max_length=50),
        ),
    ]
