# Generated by Django 4.2 on 2023-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0020_hotels_owner_image_hotels_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='cat',
        ),
        migrations.AddField(
            model_name='rooms',
            name='loan_available',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
