# Generated by Django 4.2 on 2023-05-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0021_remove_property_cat_rooms_loan_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='prop_sell',
            field=models.CharField(choices=[('1', 'For Sell'), ('2', 'For Rent/lease'), ('3', 'Not Available')], max_length=50, null=True),
        ),
    ]
