# Generated by Django 4.2 on 2023-05-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0025_rename_hotels_realator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='PropertyView',
        ),
    ]
