# Generated by Django 4.2 on 2023-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0026_rename_rooms_propertyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_in',
        ),
        migrations.AddField(
            model_name='realator',
            name='contact',
            field=models.CharField(default='987124****', max_length=50, null=True),
        ),
    ]
