# Generated by Django 4.2 on 2023-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0027_remove_reservation_check_in_realator_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='realator',
            name='intro',
            field=models.CharField(default='RealEstate Agent', max_length=350, null=True),
        ),
    ]
