# Generated by Django 4.2 on 2023-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0028_realator_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='realator',
            name='area_image',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
    ]
